In [ ]:
import pandas as pd


# rename
#  unique
# info , describe , drop, value count, shape

In [ ]:
student_data = {
    'Roll No': [101, 102, 103, 104, 105],
    'Name': ['Vishnu', 'Sarthak', 'Sanket', 'Aarav', 'Priya'],
    'Marks': [85, 92, 78, 88, 95],
    'Branch': ['CS', 'IT', 'ECE', 'ME', 'CS']
}


df = pd.DataFrame(student_data)


df

   Roll No     Name  Marks Branch
0      101   Vishnu     85     CS
1      102  Sarthak     92     IT
2      103   Sanket     78    ECE
3      104    Aarav     88     ME
4      105    Priya     95     CS

In [ ]:
# Head()

df.head(2)

   Roll No     Name  Marks Branch
0      101   Vishnu     85     CS
1      102  Sarthak     92     IT

In [8]:
# Tail()

df.tail(2)

   Roll No   Name  Marks Branch
3      104  Aarav     88     ME
4      105  Priya     95     CS

In [21]:
# iloc


df.iloc[2:5,1:4]

     Name  Marks Branch
2  Sanket     78    ECE
3   Aarav     88     ME
4   Priya     95     CS

In [24]:
# loc

df.loc[2:4, ['Name','Marks' ]]

     Name  Marks
2  Sanket     78
3   Aarav     88
4   Priya     95

In [ ]:
# add new column 


df['update_marks']=df['Marks']+10


df

   Roll No     Name  Marks Branch  Section  update_marks  new_column
0      101   Vishnu     85     CS       85            95    1.940639
1      102  Sarthak     92     IT       92           102    2.100457
2      103   Sanket     78    ECE       78            88    1.780822
3      104    Aarav     88     ME       88            98    2.009132
4      105    Priya     95     CS       95           105    2.168950

In [39]:
df

   Roll No     Name  Marks Branch  Section  update_marks  new_column
0      101   Vishnu     85     CS       85            95    1.940639
1      102  Sarthak     92     IT       92           102    2.100457
2      103   Sanket     78    ECE       78            88    1.780822
3      104    Aarav     88     ME       88            98    2.009132
4      105    Priya     95     CS       95           105    2.168950

In [ ]:
df.drop('Section' , axis=1 , inplace=True)

In [41]:
df

   Roll No     Name  Marks Branch  update_marks  new_column
0      101   Vishnu     85     CS            95    1.940639
1      102  Sarthak     92     IT           102    2.100457
2      103   Sanket     78    ECE            88    1.780822
3      104    Aarav     88     ME            98    2.009132
4      105    Priya     95     CS           105    2.168950

In [ ]:
# drop

df.drop('new_column' , axis=1 , inplace=True)

In [43]:
df

   Roll No     Name  Marks Branch  update_marks
0      101   Vishnu     85     CS            95
1      102  Sarthak     92     IT           102
2      103   Sanket     78    ECE            88
3      104    Aarav     88     ME            98
4      105    Priya     95     CS           105

In [47]:
## rename

df.rename(columns={'update_marks': 'update_marks + Internals_Marks'})

   Roll No     Name  Marks Branch  update_marks + Internals_Marks
0      101   Vishnu     85     CS                              95
1      102  Sarthak     92     IT                             102
2      103   Sanket     78    ECE                              88
3      104    Aarav     88     ME                              98
4      105    Priya     95     CS                             105

In [ ]:
## un
df['Department'].unique()