In [2]:
#pansas : it is an python free and open source
# python libraray used for data cleaning and data analysis
#and data manage 

#1. series
#2. Dataframe

In [3]:
#1. Series - 1D data format
#2. we can change column name and index
#by default column name and 0 

# index  values
#  0       10
#  1       20  
#  2       30
#  3       40

In [4]:
# dataframe -- Tabular format -- 2D data format ----table format 
# 
# example:

# index name      age
#  0    vishnu    10
#  1    sarthak   20  
#  2    vinay     30
#  3     john     40

In [5]:
import pandas  as pd

In [6]:
#creating an series 
#syntax 

# s= pd.series ([variable/element], index=[pqwer])

In [7]:
s= pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [8]:
s2= pd.Series([10,20,30,40,50], index = ['a','b','c','d','e'])
s2

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [9]:
l = [100,200,300,400,500]

s3= pd.Series(l)
s3

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [10]:
s3=pd.Series(l,index=['a','b','c','d','e'])
s3

a    100
b    200
c    300
d    400
e    500
dtype: int64

In [11]:
s3=pd.Series(l,index=['vishnu','b','c','d','e'])
s3

vishnu    100
b         200
c         300
d         400
e         500
dtype: int64

In [12]:
#indexing in series

print(s[0])

10

In [13]:
print(s[0:3])

0    10
1    20
2    30
dtype: int64

In [14]:
print(s[0:6:2])

0    10
2    30
4    50
dtype: int64

In [15]:
# series 2 function iloc and loc

In [16]:
# iloc indexing lock
# loc labled lock --- start,end,-1 not

In [17]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [18]:
s.iloc[0]

np.int64(10)

In [19]:
s.iloc[0:4]

0    10
1    20
2    30
3    40
dtype: int64

In [20]:
s3

vishnu    100
b         200
c         300
d         400
e         500
dtype: int64

In [21]:
# s3.iloc['b']

In [22]:
s3.loc['vishnu':'b']

vishnu    100
b         200
dtype: int64

In [23]:
s3.loc[['vishnu','b']]

vishnu    100
b         200
dtype: int64

In [24]:
s3.name = 'dataname'
s3

vishnu    100
b         200
c         300
d         400
e         500
Name: dataname, dtype: int64

## Dictionary

In [25]:
import pandas as pd

In [26]:
fruits= {'apple':10, 'banana':20,'orange':30,'cherry':10, 'mango':10,}

In [27]:
fruits

{'apple': 10, 'banana': 20, 'orange': 30, 'cherry': 10, 'mango': 10}

In [28]:
sdic=pd.Series(fruits)

In [29]:
## conditional operator

## DataFrame : 2D data format or tabular/table format

In [30]:
import numpy as np
data = {
'Name' : ['vishnu','sarthak','sanket'],
'Age' : [23,23,22],
'Department' : ['IT',np.nan,'TESTER'],
'Salary' : [60000,50000,40000]


}

In [31]:
data

{'Name': ['vishnu', 'sarthak', 'sanket'],
 'Age': [23, 23, 22],
 'Department': ['IT', nan, 'TESTER'],
 'Salary': [60000, 50000, 40000]}

In [32]:
df = pd.DataFrame(data)
df

      Name  Age Department  Salary
0   vishnu   23         IT   60000
1  sarthak   23        NaN   50000
2   sanket   22     TESTER   40000

In [33]:
df.head(2)

      Name  Age Department  Salary
0   vishnu   23         IT   60000
1  sarthak   23        NaN   50000

In [34]:
df.tail(3)

      Name  Age Department  Salary
0   vishnu   23         IT   60000
1  sarthak   23        NaN   50000
2   sanket   22     TESTER   40000

In [35]:
## iloc and loc

df.iloc[1:2,1:3]

   Age Department
1   23        NaN

In [36]:
df.iloc[1:3,1:3]

   Age Department
1   23        NaN
2   22     TESTER

In [37]:
## loc 

df.loc[1:2, ['Name','Age' ]]

      Name  Age
1  sarthak   23
2   sanket   22

In [38]:
df.Age

0    23
1    23
2    22
Name: Age, dtype: int64

In [39]:
df.Salary

0    60000
1    50000
2    40000
Name: Salary, dtype: int64

In [40]:
import pandas as pd

In [41]:
import pandas as pd

# drop 

df.drop('Age', axis=1)

      Name Department  Salary
0   vishnu         IT   60000
1  sarthak        NaN   50000
2   sanket     TESTER   40000

In [42]:
df

      Name  Age Department  Salary
0   vishnu   23         IT   60000
1  sarthak   23        NaN   50000
2   sanket   22     TESTER   40000

In [43]:
df.drop('Age', axis=1 ,inplace=True)

In [44]:
df

      Name Department  Salary
0   vishnu         IT   60000
1  sarthak        NaN   50000
2   sanket     TESTER   40000

In [45]:
df.drop('Salary' , axis=1)

      Name Department
0   vishnu         IT
1  sarthak        NaN
2   sanket     TESTER

In [46]:
df.drop('Salary' , axis=1 , inplace=True)

In [47]:
df

      Name Department
0   vishnu         IT
1  sarthak        NaN
2   sanket     TESTER

In [48]:
df=pd.DataFrame(data)

In [49]:
df

      Name  Age Department  Salary
0   vishnu   23         IT   60000
1  sarthak   23        NaN   50000
2   sanket   22     TESTER   40000

In [50]:
df.shape

(3, 4)

In [51]:
df.describe()

             Age   Salary
count   3.000000      3.0
mean   22.666667  50000.0
std     0.577350  10000.0
min    22.000000  40000.0
25%    22.500000  45000.0
50%    23.000000  50000.0
75%    23.000000  55000.0
max    23.000000  60000.0

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      object
 1   Age         3 non-null      int64
 2   Department  2 non-null      object
 3   Salary      3 non-null      int64
dtypes: int64(2), object(2)
memory usage: 228.0+ bytes

In [53]:
## rename  

df.rename(columns={'Name': 'Emp_Name'})

  Emp_Name  Age Department  Salary
0   vishnu   23         IT   60000
1  sarthak   23        NaN   50000
2   sanket   22     TESTER   40000

In [54]:
df.rename(columns={'Name': 'Emp_Name'} , inplace=True)

In [55]:
df

  Emp_Name  Age Department  Salary
0   vishnu   23         IT   60000
1  sarthak   23        NaN   50000
2   sanket   22     TESTER   40000

In [56]:
## uniqe

df['Department'].unique()

array(['IT', nan, 'TESTER'], dtype=object)

In [57]:
df['Department'].value_counts()

Department
IT        1
TESTER    1
Name: count, dtype: int64

In [58]:
## i want new column 

df['new_column']=df['Salary']*10

In [59]:

df

  Emp_Name  Age Department  Salary  new_column
0   vishnu   23         IT   60000      600000
1  sarthak   23        NaN   50000      500000
2   sanket   22     TESTER   40000      400000

In [60]:
import pandas as pd

In [61]:
import pandas as pd
import numpy as np

# Student dataset with 5 records (including missing values)
data = {
    'Roll No': [101, 102, 103, 104, 105],
    'Name': ['Vishnu', 'Sarthak', 'Sanket', 'Aarav', 'Priya'],
    'Marks': [85, 92, np.nan, 88, 95],
    'Branch': ['CS', 'IT', 'ECE', 'ME', np.nan]
}

# Create the DataFrame
df2 = pd.DataFrame(data)
df2

   Roll No     Name  Marks Branch
0      101   Vishnu   85.0     CS
1      102  Sarthak   92.0     IT
2      103   Sanket    NaN    ECE
3      104    Aarav   88.0     ME
4      105    Priya   95.0    NaN

In [62]:
df2.isnull().sum() ## null values , sum () --- count

Roll No    0
Name       0
Marks      1
Branch     1
dtype: int64

In [63]:
df2.dropna()

   Roll No     Name  Marks Branch
0      101   Vishnu   85.0     CS
1      102  Sarthak   92.0     IT
3      104    Aarav   88.0     ME

In [64]:
df2.dropna(how='all')

   Roll No     Name  Marks Branch
0      101   Vishnu   85.0     CS
1      102  Sarthak   92.0     IT
2      103   Sanket    NaN    ECE
3      104    Aarav   88.0     ME
4      105    Priya   95.0    NaN

In [65]:
df2.dropna(how='any')

   Roll No     Name  Marks Branch
0      101   Vishnu   85.0     CS
1      102  Sarthak   92.0     IT
3      104    Aarav   88.0     ME

In [66]:
df2

   Roll No     Name  Marks Branch
0      101   Vishnu   85.0     CS
1      102  Sarthak   92.0     IT
2      103   Sanket    NaN    ECE
3      104    Aarav   88.0     ME
4      105    Priya   95.0    NaN

In [67]:
df2.fillna('0')

   Roll No     Name Marks Branch
0      101   Vishnu  85.0     CS
1      102  Sarthak  92.0     IT
2      103   Sanket     0    ECE
3      104    Aarav  88.0     ME
4      105    Priya  95.0      0

In [68]:
df2.dropna(how='any')

   Roll No     Name  Marks Branch
0      101   Vishnu   85.0     CS
1      102  Sarthak   92.0     IT
3      104    Aarav   88.0     ME

In [69]:
df2.fillna(0)

   Roll No     Name  Marks Branch
0      101   Vishnu   85.0     CS
1      102  Sarthak   92.0     IT
2      103   Sanket    0.0    ECE
3      104    Aarav   88.0     ME
4      105    Priya   95.0      0

In [70]:
df2

   Roll No     Name  Marks Branch
0      101   Vishnu   85.0     CS
1      102  Sarthak   92.0     IT
2      103   Sanket    NaN    ECE
3      104    Aarav   88.0     ME
4      105    Priya   95.0    NaN

In [71]:
df2['Marks'].fillna(df2['Marks'].mean())

0    85.0
1    92.0
2    90.0
3    88.0
4    95.0
Name: Marks, dtype: float64

In [72]:
df2['Marks'].fillna(df2['Marks'].median())

0    85.0
1    92.0
2    90.0
3    88.0
4    95.0
Name: Marks, dtype: float64

In [73]:
## forward fill 

df2['Marks'].fillna(method ='ffill')

C:\Users\vishn\AppData\Local\Temp\ipykernel_18352\3571456159.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2['Marks'].fillna(method ='ffill')

0    85.0
1    92.0
2    92.0
3    88.0
4    95.0
Name: Marks, dtype: float64

In [74]:
## backward fill 

df2['Marks'].fillna(method ='bfill')

C:\Users\vishn\AppData\Local\Temp\ipykernel_18352\4284821960.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2['Marks'].fillna(method ='bfill')

0    85.0
1    92.0
2    88.0
3    88.0
4    95.0
Name: Marks, dtype: float64

In [75]:
df2

   Roll No     Name  Marks Branch
0      101   Vishnu   85.0     CS
1      102  Sarthak   92.0     IT
2      103   Sanket    NaN    ECE
3      104    Aarav   88.0     ME
4      105    Priya   95.0    NaN

In [76]:
##  replace / duplicate

df2['Name'] = df2['Name'].replace('Priya','Aarav')

In [77]:
df2

   Roll No     Name  Marks Branch
0      101   Vishnu   85.0     CS
1      102  Sarthak   92.0     IT
2      103   Sanket    NaN    ECE
3      104    Aarav   88.0     ME
4      105    Aarav   95.0    NaN

In [78]:
df2

   Roll No     Name  Marks Branch
0      101   Vishnu   85.0     CS
1      102  Sarthak   92.0     IT
2      103   Sanket    NaN    ECE
3      104    Aarav   88.0     ME
4      105    Aarav   95.0    NaN

In [79]:
import pandas as pd
import numpy as np

# Student dataset with 5 records (including missing values)
data = {
    'seating_': [101, 102, 103, 104, 105],
    'Name': ['Vishnu', 'Sarthak', 'Sanket', 'Aarav', 'Priya'],
    'Age': [85, 92, np.nan, 88, 95],
    'Branch': ['CS', 'IT', 'ECE', 'ME', np.nan]
}

# Create the DataFrame
df3 = pd.DataFrame(data)
df3

   seating_     Name   Age Branch
0       101   Vishnu  85.0     CS
1       102  Sarthak  92.0     IT
2       103   Sanket   NaN    ECE
3       104    Aarav  88.0     ME
4       105    Priya  95.0    NaN

In [80]:
df3['Name'] = df3['Name'].replace('Priya','Aarav')

In [81]:
df3

   seating_     Name   Age Branch
0       101   Vishnu  85.0     CS
1       102  Sarthak  92.0     IT
2       103   Sanket   NaN    ECE
3       104    Aarav  88.0     ME
4       105    Aarav  95.0    NaN

In [82]:
df3['Age'] = df3['Age'].replace(95.0,88.0)

In [83]:
df3

   seating_     Name   Age Branch
0       101   Vishnu  85.0     CS
1       102  Sarthak  92.0     IT
2       103   Sanket   NaN    ECE
3       104    Aarav  88.0     ME
4       105    Aarav  88.0    NaN

In [84]:
df3['Branch'] = df3['Branch'].replace('Nan','ME')

In [85]:
df3

   seating_     Name   Age Branch
0       101   Vishnu  85.0     CS
1       102  Sarthak  92.0     IT
2       103   Sanket   NaN    ECE
3       104    Aarav  88.0     ME
4       105    Aarav  88.0    NaN

In [86]:
df3['seating_'] = df3['seating_'].replace(105,104)

In [87]:
df3

   seating_     Name   Age Branch
0       101   Vishnu  85.0     CS
1       102  Sarthak  92.0     IT
2       103   Sanket   NaN    ECE
3       104    Aarav  88.0     ME
4       104    Aarav  88.0    NaN

In [88]:
## duplicate

dup = df3 [df3.duplicated(keep='last')]
dup

Empty DataFrame
Columns: [seating_, Name, Age, Branch]
Index: []

In [89]:
dup

Empty DataFrame
Columns: [seating_, Name, Age, Branch]
Index: []

In [90]:
l_dup = df3 [df3.duplicated(keep='first')]

In [91]:
l_dup

Empty DataFrame
Columns: [seating_, Name, Age, Branch]
Index: []

In [92]:
df3

   seating_     Name   Age Branch
0       101   Vishnu  85.0     CS
1       102  Sarthak  92.0     IT
2       103   Sanket   NaN    ECE
3       104    Aarav  88.0     ME
4       104    Aarav  88.0    NaN

In [93]:
df2

   Roll No     Name  Marks Branch
0      101   Vishnu   85.0     CS
1      102  Sarthak   92.0     IT
2      103   Sanket    NaN    ECE
3      104    Aarav   88.0     ME
4      105    Aarav   95.0    NaN

In [94]:
df2['Marks']=df2['Marks'].apply(lambda x : x * 1.1)
df2

   Roll No     Name  Marks Branch
0      101   Vishnu   93.5     CS
1      102  Sarthak  101.2     IT
2      103   Sanket    NaN    ECE
3      104    Aarav   96.8     ME
4      105    Aarav  104.5    NaN

In [95]:
# lambada in pandas

In [96]:
import pandas as pd

pd.concat([df2,df3])

   Roll No     Name  Marks Branch  seating_   Age
0    101.0   Vishnu   93.5     CS       NaN   NaN
1    102.0  Sarthak  101.2     IT       NaN   NaN
2    103.0   Sanket    NaN    ECE       NaN   NaN
3    104.0    Aarav   96.8     ME       NaN   NaN
4    105.0    Aarav  104.5    NaN       NaN   NaN
0      NaN   Vishnu    NaN     CS     101.0  85.0
1      NaN  Sarthak    NaN     IT     102.0  92.0
2      NaN   Sanket    NaN    ECE     103.0   NaN
3      NaN    Aarav    NaN     ME     104.0  88.0
4      NaN    Aarav    NaN    NaN     104.0  88.0

In [97]:
merg= pd.concat([df2,df3])
merg

   Roll No     Name  Marks Branch  seating_   Age
0    101.0   Vishnu   93.5     CS       NaN   NaN
1    102.0  Sarthak  101.2     IT       NaN   NaN
2    103.0   Sanket    NaN    ECE       NaN   NaN
3    104.0    Aarav   96.8     ME       NaN   NaN
4    105.0    Aarav  104.5    NaN       NaN   NaN
0      NaN   Vishnu    NaN     CS     101.0  85.0
1      NaN  Sarthak    NaN     IT     102.0  92.0
2      NaN   Sanket    NaN    ECE     103.0   NaN
3      NaN    Aarav    NaN     ME     104.0  88.0
4      NaN    Aarav    NaN    NaN     104.0  88.0

In [98]:
df = pd.read_excel("D:/SOFTRONIX/SQL/order_items.xlsx")
df

    order_item_id  order_id  product_id  quantity  total_price
0               1       101           1         1        45000
1               2       101          11         2         6000
2               3       102           3         1        30000
3               4       103           2         1        15000
4               5       104           4         1        25000
5               6       105           7         3         9000
6               7       106           5         1        10000
7               8       107           8         1        40000
8               9       108           6         1        35000
9              10       109           9         1         8000
10             11       110          12         2        10000
11             12       111           2         1        15000
12             13       112          10         1         5000
13             14       113           3         1        30000
14             15       114          13         2        24000
15             16       115          14         1        55000
16             17       116          15         1        35000
17             18       117          16         3         6000
18             19       118          17         1         7000
19             20       119          19         2         7000
20             21       120          18         1         1500
21             22       121          20        10         2500
22             23       122           8         1        40000
23             24       123           6         1        35000
24             25       124           5         2        20000
25             26       125           9         1         8000
26             27       126          12         1         5000
27             28       127           4         1        25000
28             29       128          14         1        55000
29             30       129          17         2        14000